<a href="https://colab.research.google.com/github/JorgeHernandezRivera/datathon_2023/blob/main/Reto_Dataton_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Carga de Datos

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/JorgeHernandezRivera/datathon_2023/main/data/clean_by_model.csv')

**Se subieron los datos limpios resultantes del cuaderno anterior de EDA al repositorio para no cargarlos manualmente desde este cuaderno de COLAB**

In [ ]:
df.head()

Posición Area Liquidación   Grupo  CODIGO POSTAL          Motivo_Renuncia  \
0   POS514  LOG          S6  Exempt          32520          Vol-Otro empleo   
1  POS1745  MFS          S5  Direct          32217          Vol-Otro empleo   
2  POS1230  VS7          S5  Direct          32600          Vol-Otro empleo   
3  POS1661  MFS          S5  Direct          32575             Vol-Estudios   
4  POS1921  MFS          S5  Direct          32575  Vol-Cambio de domicilio   

  Nivel_Salarial  Fecha_Baja Regla_PHT  Fecha_Alta  ...     Genero  \
0             E3  2023-01-02  ADMINIST  2018-06-21  ...   Femenino   
1            DNO  2023-01-03  ADMINIST  2017-07-20  ...  Masculino   
2            DNO  2023-01-03  JT012324  2019-08-29  ...  Masculino   
3             DO  2023-01-03  JT012324  2022-11-03  ...   Femenino   
4             DO  2023-01-03  JT012324  2017-03-02  ...  Masculino   

   Lugar_Nacimiento  Nacionalidad Edad Tiempo_CDJuarez Estado_Civil  \
0     CIUDAD JUAREZ       Mexican   31       10+ Years      Soltero   
1           DURANGO       Mexican   25       10+ Years      Soltero   
2     CIUDAD JUAREZ       Mexican   23       10+ Years      Soltero   
3     CIUDAD JUAREZ       Mexican   18       10+ Years      Soltero   
4     CIUDAD JUAREZ       Mexican   26       10+ Years      Soltero   

   Numero_Hijos RangoEdad Mes_Baja  Año_Baja  
0             0     26-35        1      2023  
1             0     26-35        1      2023  
2             0     19-25        1      2023  
3             0     19-25        1      2023  
4             0     26-35        1      2023  

[5 rows x 23 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1403 entries, 0 to 1402
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Posición          1403 non-null   object 
 1   Area              1403 non-null   object 
 2   Liquidación       1403 non-null   object 
 3   Grupo             1403 non-null   object 
 4   CODIGO POSTAL     1403 non-null   int64  
 5   Motivo_Renuncia   1403 non-null   object 
 6   Nivel_Salarial    1403 non-null   object 
 7   Fecha_Baja        1403 non-null   object 
 8   Regla_PHT         1403 non-null   object 
 9   Fecha_Alta        1403 non-null   object 
 10  Años              1403 non-null   int64  
 11  Meses             1403 non-null   float64
 12  Antigüedad        1403 non-null   int64  
 13  Genero            1403 non-null   object 
 14  Lugar_Nacimiento  1403 non-null   object 
 15  Nacionalidad      1403 non-null   object 
 16  Edad              1403 non-null   int64  


In [ ]:
df['Motivo_Renuncia'].value_counts().head(15)

Vol-Otro empleo                     308
Vol-Transferencia entre planta      237
Vol-No regreso / no dio razón       218
Vol-Prob personales y/o fam.        197
Vol-Insatisfacción personal          94
Vol-Cambio de domicilio              89
Imp.Tra-Ausentismos continuos        71
Vol-Estudios                         68
Imp.Tra-Jubilación                   33
Vol-Razones médicas                  28
Imp.Tra-LFT y/o Reglamento int       12
Imp.Tra-LFT y/o Reglamento Int.      12
Imp.Pat-Pensionado IMSS               8
Imp.Pat-Terminación del Contrato      6
Imp.Tra-Bajo desempeño                3
Name: Motivo_Renuncia, dtype: int64

**Viendo los principales 15 motivos de renuncia para la determinacion del modelo de clasificacion multiclase**

# Top 15 valores principales y Top 5 valores principales

In [ ]:
top_15_motivos = df['Motivo_Renuncia'].value_counts().head(15).index.tolist()
top_5_motivos = df['Motivo_Renuncia'].value_counts().head(5).index.tolist()

# Filtro del dataframe original y auxiliar de acuerdo al top 15 y top5
df = df[df['Motivo_Renuncia'].isin(top_15_motivos)]
df_adicional = df[df['Motivo_Renuncia'].isin(top_5_motivos)]


**Se dividio de esta manera para poder gestionar el futuro multiclase con mayor exactitud**

In [ ]:
df['Motivo_Renuncia'].value_counts()

Vol-Otro empleo                     308
Vol-Transferencia entre planta      237
Vol-No regreso / no dio razón       218
Vol-Prob personales y/o fam.        197
Vol-Insatisfacción personal          94
Vol-Cambio de domicilio              89
Imp.Tra-Ausentismos continuos        71
Vol-Estudios                         68
Imp.Tra-Jubilación                   33
Vol-Razones médicas                  28
Imp.Tra-LFT y/o Reglamento int       12
Imp.Tra-LFT y/o Reglamento Int.      12
Imp.Pat-Pensionado IMSS               8
Imp.Pat-Terminación del Contrato      6
Imp.Tra-Bajo desempeño                3
Name: Motivo_Renuncia, dtype: int64

In [ ]:
df_adicional['Motivo_Renuncia'].value_counts()

Vol-Otro empleo                   308
Vol-Transferencia entre planta    237
Vol-No regreso / no dio razón     218
Vol-Prob personales y/o fam.      197
Vol-Insatisfacción personal        94
Name: Motivo_Renuncia, dtype: int64

# Preparacion Datos


In [ ]:
#Borrar columnas innecesarias para el modelo
df = df.drop(['Posición','CODIGO POSTAL','Fecha_Baja','Fecha_Alta','Antigüedad','Lugar_Nacimiento','Nacionalidad',
         'RangoEdad','Mes_Baja','Año_Baja'],axis=1)

df_adicional = df_adicional.drop(['Posición','CODIGO POSTAL','Fecha_Baja','Fecha_Alta','Antigüedad','Lugar_Nacimiento','Nacionalidad',
         'RangoEdad','Mes_Baja','Año_Baja'],axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1384 entries, 0 to 1402
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             1384 non-null   object 
 1   Liquidación      1384 non-null   object 
 2   Grupo            1384 non-null   object 
 3   Motivo_Renuncia  1384 non-null   object 
 4   Nivel_Salarial   1384 non-null   object 
 5   Regla_PHT        1384 non-null   object 
 6   Años             1384 non-null   int64  
 7   Meses            1384 non-null   float64
 8   Genero           1384 non-null   object 
 9   Edad             1384 non-null   int64  
 10  Tiempo_CDJuarez  1384 non-null   object 
 11  Estado_Civil     1384 non-null   object 
 12  Numero_Hijos     1384 non-null   int64  
dtypes: float64(1), int64(3), object(9)
memory usage: 151.4+ KB


In [ ]:
df_adicional.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1054 entries, 0 to 1400
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             1054 non-null   object 
 1   Liquidación      1054 non-null   object 
 2   Grupo            1054 non-null   object 
 3   Motivo_Renuncia  1054 non-null   object 
 4   Nivel_Salarial   1054 non-null   object 
 5   Regla_PHT        1054 non-null   object 
 6   Años             1054 non-null   int64  
 7   Meses            1054 non-null   float64
 8   Genero           1054 non-null   object 
 9   Edad             1054 non-null   int64  
 10  Tiempo_CDJuarez  1054 non-null   object 
 11  Estado_Civil     1054 non-null   object 
 12  Numero_Hijos     1054 non-null   int64  
dtypes: float64(1), int64(3), object(9)
memory usage: 115.3+ KB


# Codificacion variables categoricas

Es necesario codificar las variables categoricas para poder usar el modelo de manera adecuada, incluida la variable objetivo en ambos dataframes

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Lista de columnas categóricas que quieres codificar
columnas_categoricas = ['Area', 'Liquidación', 'Grupo', 'Motivo_Renuncia', 'Nivel_Salarial',
                         'Regla_PHT', 'Genero', 'Tiempo_CDJuarez', 'Estado_Civil']

# Aplica LabelEncoder a cada columna categórica
label_encoder = LabelEncoder()
for columna in columnas_categoricas:
    df[columna] = label_encoder.fit_transform(df[columna])
    df_adicional[columna] = label_encoder.fit_transform(df_adicional[columna])

# Ahora, las columnas categóricas tienen valores numéricos asignados
df.head()

Area  Liquidación  Grupo  Motivo_Renuncia  Nivel_Salarial  Regla_PHT  Años  \
0     6            1      1               11               2          0     5   
1     7            0      0               11               0          0     6   
2    14            0      0               11               0          5     4   
3     7            0      0                8               1          5     1   
4     7            0      0                7               1          5     6   

       Meses  Genero  Edad  Tiempo_CDJuarez  Estado_Civil  Numero_Hijos  
0  55.200000       0    31                2             5             0  
1  66.433333       1    25                2             5             0  
2  40.766667       1    23                2             5             0  
3   2.033333       0    18                2             5             0  
4  71.100000       1    26                2             5             0

In [ ]:
df_adicional.head()

Area  Liquidación  Grupo  Motivo_Renuncia  Nivel_Salarial  Regla_PHT  Años  \
0     6            1      1                2               2          0     5   
1     7            0      0                2               0          0     6   
2    14            0      0                2               0          5     4   
5    10            0      0                2               0          2     5   
7     7            0      0                2               1          3     3   

       Meses  Genero  Edad  Tiempo_CDJuarez  Estado_Civil  Numero_Hijos  
0  55.200000       0    31                2             4             0  
1  66.433333       1    25                2             4             0  
2  40.766667       1    23                2             4             0  
5  52.666667       1    38                2             0             3  
7  24.900000       0    27                2             4             1

# Division de Datos

**Se dividiran los datos de acuerdo a un porcentaje de 80-20 en entrenamiento y prueba**

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('Motivo_Renuncia', axis=1)
y = df['Motivo_Renuncia']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Modelos

**Los modelos de clasificacion que se usaran son los siguientes:**

* RandomForestClassifier
* DecisionTreeClassifier
* LogisticRegression

## RandomForestClassifier

**Contexto de Uso:**

* Ideal para problemas de clasificación, especialmente cuando hay un gran número de características o variables predictivas.
* Útil cuando se busca un modelo robusto y resistente al sobreajuste.
* Capaz de manejar automáticamente la importancia de las características y manejar conjuntos de datos grandes y complejos.

**Características del Modelo:**

* Ensamble de árboles de decisión.
* Cada árbol se entrena con una muestra diferente del conjunto de datos y las predicciones se combinan para obtener una predicción final.
* Puede manejar tanto problemas de clasificación como de regresión.

**Consideraciones:**

* Puede ser propenso a sobreajuste en conjuntos de datos pequeños con ruido.
* Ofrece una buena interpretabilidad de las características más importantes.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         2
           2       0.09      0.07      0.08        14
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.08      0.07      0.07        15
           8       0.14      0.10      0.12        10
           9       0.00      0.00      0.00        21
          10       0.53      0.65      0.58        46
          11       0.40      0.50      0.45        68
          12       0.22      0.29      0.25        38
          13       0.00      0.00      0.00         4
          14       0.21      0.17      0.19        53

    accuracy                           0.32       277
   macro avg       0.18      0.19      0.18       277
weighted avg       0.27   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Mejora del modelo

**Se realiza una búsqueda exhaustiva de hiperparámetros para el modelo utilizando la clase GridSearchCV, y luego utiliza el mejor modelo encontrado para hacer predicciones en un conjunto de prueba.**

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'n_estimators': [50, 100, 200], 'max_depth': [None, 10, 20]}
grid_search = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=3)
grid_search.fit(X_train, y_train)
best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(


**La búsqueda de hiperparámetros nos puede ayudar a encontrar la combinación óptima que mejora el rendimiento del modelo en función de la métrica de evaluación seleccionada (por defecto, la precisión).**

### Metricas

In [ ]:
#Matriz de confusion
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de Confusión:")
print(conf_matrix)


Matriz de Confusión:
[[ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  5  4  2  0  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  1  1  6  5  0  1]
 [ 0  0  0  0  0  0  0  0  1  0  1  4  1  0  3]
 [ 0  0  0  0  0  0  0  1  0  0  0 10  4  0  6]
 [ 0  0  1  0  0  0  0  0  0  0 35  2  5  0  3]
 [ 0  0  0  0  0  0  0  0  1  0  1 46  8  0 12]
 [ 0  0  0  0  0  0  0  1  1  0 10  8 10  0  8]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  2  0  1]
 [ 0  1  0  0  0  0  0  0  1  0  3 25 15  0  8]]


**La matriz de confusión es útil para evaluar el rendimiento del modelo, especialmente en problemas de clasificación. Proporciona información sobre cuántas instancias fueron clasificadas correctamente y cuántas fueron clasificadas incorrectamente para cada clase.**



```
[[TN  FP]
 [FN  TP]]

```
* TN (True Negatives): Instancias que fueron clasificadas correctamente como negativas.
* FP (False Positives): Instancias que fueron clasificadas incorrectamente como positivas.
* FN (False Negatives): Instancias que fueron clasificadas incorrectamente como negativas.
* TP (True Positives): Instancias que fueron clasificadas correctamente como positivas.


In [ ]:
#Exactitud
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"Exactitud del modelo: {accuracy}")

Exactitud del modelo: 0.36462093862815886


La exactitud es una métrica comúnmente utilizada para evaluar modelos de clasificación y se calcula mediante la fórmula:

![](https://live.staticflickr.com/65535/48051257888_760554732e_b.jpg)

La exactitud es una métrica útil, pero su interpretación puede verse afectada por el desequilibrio de clases. En casos de clases desequilibradas, puede ser beneficioso considerar otras métricas como precisión, recall o F1-score.

In [ ]:
#Precisión, Recall y F1-Score
from sklearn.metrics import classification_report

classification_rep = classification_report(y_test, y_pred)
print("Reporte de Clasificación:")
print(classification_rep)


Reporte de Clasificación:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00        14
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00        15
           8       0.20      0.10      0.13        10
           9       0.00      0.00      0.00        21
          10       0.62      0.76      0.69        46
          11       0.41      0.68      0.51        68
          12       0.19      0.26      0.22        38
          13       0.00      0.00      0.00         4
          14       0.17      0.15      0.16        53

    accuracy                           0.36       277
   macro avg       0.17      0.20      0.18       277


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**El informe de clasificación proporciona una visión detallada del rendimiento del modelo para cada clase.**

Precisión (Precision): La proporción de instancias clasificadas como positivas que son verdaderamente positivas.

Recall (Sensibilidad o True Positive Rate): La proporción de instancias positivas que fueron correctamente identificadas por el modelo.

![](https://miro.medium.com/v2/resize:fit:888/1*7J08ekAwupLBegeUI8muHA.png)



F1-Score: La media armónica de precisión y recall. Es útil cuando hay un desequilibrio entre precisión y recall.

![](https://inside-machinelearning.com/wp-content/uploads/2021/09/F1-Score.png)

Support: El número total de instancias en cada clase.

## DecisionTreeClassifier

**Contexto de Uso:**

* Adecuado para problemas de clasificación y regresión.
* Útil cuando se busca un modelo interpretable y fácil de visualizar.
* Puede ser una buena opción para conjuntos de datos pequeños y limpios.

**Características del Modelo:**

* Crea un árbol de decisiones basado en las características del conjunto de datos.
* Cada nodo en el árbol representa una decisión basada en una característica.
* Puede manejar datos categóricos y numéricos.

**Consideraciones:**

* Puede ser propenso al sobreajuste, especialmente en conjuntos de datos complejos o ruidosos.
* Puede requerir técnicas de ajuste de hiperparámetros para evitar sobreajuste.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# Crea y entrena el modelo DecisionTreeClassifier
tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(X_train, y_train)

# Realiza predicciones en el conjunto de prueba
y_pred_tree = tree_model.predict(X_test)

# Evalúa el rendimiento del modelo
accuracy_tree = accuracy_score(y_test, y_pred_tree)
print(f"Exactitud del modelo DecisionTreeClassifier: {accuracy_tree}\n")

# Imprime el informe de clasificación y otras métricas si lo deseas
print("Reporte de Clasificación para DecisionTreeClassifier:")
print(classification_report(y_test, y_pred_tree))


Exactitud del modelo DecisionTreeClassifier: 0.259927797833935

Reporte de Clasificación para DecisionTreeClassifier:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         2
           2       0.16      0.21      0.18        14
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.04      0.07      0.05        15
           8       0.00      0.00      0.00        10
           9       0.12      0.10      0.11        21
          10       0.53      0.54      0.54        46
          11       0.38      0.35      0.37        68
          12       0.11      0.11      0.11        38
          13       0.00      0.00      0.00         4
          14       0.27      0.23      0.24        53

    accuracy    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## LogisticRegression

**Contexto de Uso:**

* Adecuado para problemas de clasificación binaria y multiclase.
* Útil cuando se busca un modelo lineal que funcione bien con características lineales o aproximadamente lineales.
* Puede ser una buena opción para problemas con interpretación de coeficientes.

**Características del Modelo:**

* Modelo lineal que utiliza la función logística para producir salidas entre 0 y 1.
* Se puede entender como la probabilidad de pertenecer a una clase en lugar de una predicción directa de la clase.

**Consideraciones:**

* No es adecuado para relaciones no lineales entre características y resultado.
* Sensible a valores atípicos en los datos.
* Puede requerir preprocesamiento adicional para manejar multicolinealidad u otros problemas.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# Crea y entrena el modelo LogisticRegression
logreg_model = LogisticRegression(random_state=42)
logreg_model.fit(X_train, y_train)

# Realiza predicciones en el conjunto de prueba
y_pred_logreg = logreg_model.predict(X_test)

# Evalúa el rendimiento del modelo
accuracy_logreg = accuracy_score(y_test, y_pred_logreg)
print(f"Exactitud del modelo LogisticRegression: {accuracy_logreg}\n")

print("Reporte de Clasificación para LogisticRegression:")
print(classification_report(y_test, y_pred_logreg))


Exactitud del modelo LogisticRegression: 0.3574007220216607

Reporte de Clasificación para LogisticRegression:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00        14
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00        15
           8       0.00      0.00      0.00        10
           9       0.00      0.00      0.00        21
          10       0.38      0.67      0.49        46
          11       0.45      0.72      0.55        68
          12       0.32      0.24      0.27        38
          13       0.00      0.00      0.00         4
          14       0.18      0.19      0.19        53

    accuracy           

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels wit

**En general los modelos tienen muy poca exactitud pero esto es debido a las multiclases que existen, que pasa si trabajamos con solo 5 clases de Motivo_Renuncia?**

# Prueba del modelo con solo 5 clases en Motivo_Renuncia

**Se probara como funciona el modelo de acuerdo a solo 5 de las principales clases de la columna objetivo Motivo_Renuncia**

## Division Datos

In [ ]:
df_adicional['Motivo_Renuncia'].value_counts()

2    308
4    237
1    218
3    197
0     94
Name: Motivo_Renuncia, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X = df_adicional.drop('Motivo_Renuncia', axis=1)
y = df_adicional['Motivo_Renuncia']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Modelo RandomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.12      0.06      0.08        16
           1       0.74      0.64      0.69        53
           2       0.64      0.67      0.66        70
           3       0.30      0.41      0.35        34
           4       0.34      0.34      0.34        38

    accuracy                           0.52       211
   macro avg       0.43      0.43      0.42       211
weighted avg       0.52      0.52      0.51       211



In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'n_estimators': [50, 100, 200], 'max_depth': [None, 10, 20]}
grid_search = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=3)
grid_search.fit(X_train, y_train)
best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

In [ ]:
#Matriz de confusion
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de Confusión:")
print(conf_matrix)

Matriz de Confusión:
[[ 0  1  9  4  2]
 [ 0 32  3 10  8]
 [ 1  2 51  6 10]
 [ 0  6  4 14 10]
 [ 0  2 10 11 15]]


In [ ]:
#Exactitud
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"Exactitud del modelo: {accuracy}")

Exactitud del modelo: 0.5308056872037915


In [ ]:
#Precisión, Recall y F1-Score
from sklearn.metrics import classification_report

classification_rep = classification_report(y_test, y_pred)
print("Reporte de Clasificación:")
print(classification_rep)

Reporte de Clasificación:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        16
           1       0.74      0.60      0.67        53
           2       0.66      0.73      0.69        70
           3       0.31      0.41      0.35        34
           4       0.33      0.39      0.36        38

    accuracy                           0.53       211
   macro avg       0.41      0.43      0.42       211
weighted avg       0.52      0.53      0.52       211



**El modelo tiene mejor exactitud al disminuir el numero de clases, sin embargo se debe considerar hacer una mejor codificacion de las variables categoricas a futuro o considerar optar por redes neuronales para poder entrenar el modelo de manera mas adecuada**

# Exportar modelo

In [ ]:
!pip install joblib

In [ ]:
import joblib

# Guardar el modelo en un archivo
joblib.dump(best_model, 'modelo.joblib')


['modelo.joblib']